global:
  scrape_interval: 5s
  evaluation_interval: 5s
  labels:
    monitor: stackengine-blog-metrics

rule_files:

scrape_configs:
- job_name: prometheus-scraper
  scrape_interval: 5s

  target_groups:
    # These endpoints are scraped via HTTP.
    - targets: ['localhost:9090','192.168.99.100:9777']
